### ISSUE TITLE
Main.sol deployment 

### ISSUE THREAD

**Issue by terraarret** [MaastrichtU-IDS/DecentralizedHealthcareBackend#17]
When deploying the Main.sol contract using:
tx_hash = YourContract.constructor().transact()
The constructor requires two values: verifier and commitment. 
I believe that the verifier is the address of a deployed IVerifier contract, so the PlonkVerifier.sol needs to be deployed first. Is this correct?
While for the commitment I believe it's an array that sets the boolean variables corresponding to the data provider's preferences. If this is the case what are the size and range of accepted values?

File: https://file.io/hbW8gHvlkwCD

**Comment by klifish** [comment]
You need to deploy smart contracts with LUCE APIs, which provide proper context for them
