### ISSUE TITLE
Contract info 2

### ISSUE THREAD

**Issue by terraarret** [MaastrichtU-IDS/DecentralizedHealthcareBackend#25]
Dear Kun, @klifish 

I'm not sure which info the data requester has to provide (because I lost access to Postman).

Are these the following?

// giveResearchPurpose
 function giveResearchPurpose(
        address _address2,
        bool _UseForMethodsDevelopment,
        bool _UseForReferenceOrControlMaterial,
        bool _UseForPopulationsResearch,
        bool _UseForAncestryResearch,
        bool _UseForHMBResearch)
// giveHMBPurpose
 function giveHMBPurpose( 
        address _address2, 
        bool _UseForFundamentalBioResearch,
        bool _UseForGeneticsResearch,
        bool _UseForDrugDevelopmentResearch, 
        bool _UseForAnyDiseaseResearch,
        bool _UseForAgeCategoriesResearch,
        bool _UseForGenderCategoriesResearch)
// giveClinicalPurpose
 function giveClinicalPurpose( 
        address _address2, 
        bool _UseForDecisionSupport, 
        bool _UseForDiseaseSupport)
// givePerson
function givePerson( 
        address _address2,
        bool _UseByAcademicProfessionals,
        bool _UseByClinicalProfessionals,
        bool _UseByProfitMakingProfessionals, 
        bool _UseByNonProfessionals)
// giveGeographicSpecificRestriction
 function giveGeographicSpecificRestriction( 
        address _address2, 
        bool _UseBySpecifiedCountries)
// giveProfit
 function giveProfit( 
        address _address2, 
        bool _UseForProfitPurpose,
        bool _UseForNonProfitPurpose)
//giveDataRequester_Terms
 function giveDataRequester_Terms( 
        address _address2, 
        bool _NoTimelineRestrictions,
        bool _NoFormalApprovalRequired,
        bool _NoCollaborationRequired,
        bool _NoPublicationRequired,
        bool _NoDataSecurityMeasures,
        bool _NoDataDestructionRequired,
        bool _NoLinkingOfAccessedRecords,
        bool _NoRecontactingDataSubjects,
        bool _NoIntellectualPropertyClaims,
        bool _NoUseOfAccessedResources,
        bool _NoFeesForAccess)

**Comment by klifish** [comment]
You can find LUCE API here:
https://documenter.getpostman.com/view/18666298/2s93sZ7aDm
@terraarret
